version: '3.9'
services:
  mysql:
    image: mysql:latest
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: account_service
      MYSQL_SSL_MODE: DISABLED # Disable SSL
      MYSQL_INIT_CONNECT: SET GLOBAL ssl_disabled = 'YES'
    ports:
      - 3306:3306

  flyway:
    image: flyway/flyway
    restart: on-failure
    command: -url=jdbc:mysql://mysql:3306/account_service?useSSL=false -user=username -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql

  accountservice:
    build: .
    container_name: accountservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql
