apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-pod
  template:
    metadata:
      labels:
        app: account-service-pod
    spec:
      containers:
        - name: account-service
          image: account-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: account-service-app-service
spec:
  selector:
    app: account-service-pod
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
